![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# **$$ ⛳ \textbf{ Create Algorithm with Python for the Four Perspective of Matrix Multiplications }⛳ $$**
# **$$ ⛳ \textbf{ and Build Matrix Multiplication Layer-Wise with Outer Product }⛳ $$**


<details>
  <summary><b>Show Diagrams of Four Perspectives of Matrix Multiplications</b></summary>
  
<p style="text-align:center;"><img src = "https://drive.google.com/uc?id=1wVN7pHMcvao5kINzE5I3uVxZVMqhRDMh" width = "900px" height = "600px" />
</details>

Watch this [video](https://www.3cmediasolutions.org/privid/388761?key=80917d5390fd86322a2160cb3e2ca310a0d7c5b5) on how to create a link in Markdown to an image on Google Drive.


### **Four Perspective Matrix Multiplications** in [google slide format](https://docs.google.com/presentation/d/1A_WdwIEFiQIH7y50wrXjLmFsBpu_T9DUctUFm7t01m4/edit?usp=share_link)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## **Objective:**

####  Implementation of the four perpective matrix multiplications in Python.

#### ⛽ There are many resources for writing text in markdown and mathematics typesets in latex.  Here is one for matrix
[How to write matrices in Latex ?](https://www.math-linux.com/latex-26/faq/latex-faq/article/how-to-write-matrices-in-latex-matrix-pmatrix-bmatrix-vmatrix-vmatrix)

[Markdown Cheatsheet.]( https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

🚥 But keep in mind that these numerical demonstrations in a couple of examples are not formal mathematical proofs, and these are not substitutes for formal mathematical proofs. These are just really great ways to help you internalize the concepts.

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## ⏰ **Resource for syntax**


### **1.** Create a random matrix of the size $m\times n$: `numpy.random.randn(m,n)`
### **2.** Create a matrix of all zeros of the size $m\times n$: `numpy.zeros((m, n))`
### **3.** Create an empty matrix of the size $m\times n$: `numpy.empty((m, n))`
### **4.** Slice the $i$th row  from a matrix: `A[ : , i]` 
### **5.** Slice the $j$th column  from a matrix: `B[ j, :]`
### **6.** Select the element at the $i$th row and $j$th column form a matrix A:  `A[ i, j]` or  `A[ i ][ j ]`
### **7.** Round all elements in a matrix A to 1 decimal place value: `numpy.round(A, 1)`. (Default with no decimal place value  `numpy.round(A)`

### Other methods in numpy for matrix are found [here](https://numpy.org/doc/stable/reference/generated/numpy.empty.html)


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## **TODOs**

---
### **$\color{brown}{\textbf{TODO 1: }}$ Review Matrix Multiplications from four perspectives**
<details>
  <summary><b>Show Diagrams of Four Perspectives of Matrix Multiplications</b></summary>
  
<p style="text-align:center;"><img src = "https://drive.google.com/uc?id=1wVN7pHMcvao5kINzE5I3uVxZVMqhRDMh" width = "900px" height = "600px" />
</details>

Watch this [video](https://www.3cmediasolutions.org/privid/388761?key=80917d5390fd86322a2160cb3e2ca310a0d7c5b5) on how to create a link in Markdown to an image on Google Drive.

### **Four Perspective Matrix Multiplications** in [google slide format](https://docs.google.com/presentation/d/1A_WdwIEFiQIH7y50wrXjLmFsBpu_T9DUctUFm7t01m4/edit?usp=share_link)


---
### **$\color{brown}{\textbf{TODO 2: }}$** Implement the **"element" perspective** matrix multiplication of matrices $\mathbf{A}$ and $\mathbf{B}$ with integer elements matrices of small sizes.

* Explain or illustrate your algorithm
* Implement the algorithm in ptyhon code
* Verify your code by computing the multiplication with python library
* print out the result


In [33]:
import numpy as np

A = np.array([
              [2, 3],
              [4, 5], 
              [1, 1]
])

# get row or column length
# you do not have to define this variable, but directly use .shape[0]: row, .shape[1]: column

n_row_A, n_col_A = A.shape
print(f"Select col 0 of A: A[ : , 0 ] = {A[:, 0]}")
print(f"Select row 2 of A: A[ 2 , : ] = {A[2, :]}")
print(f"Select element in row = 0 , col = 1 , A[row, col] or A[row][col] = {A[0, 1]}")
print(f"The size of A = (A.shape[0], A.shape[1]) = {A.shape[0], A.shape[1]}")


B = np.array([
              [5, 6],
              [7, 8]
])

# get row or column length
# you do not have to define this variable, but directly use .shape[0]: row, .shape[1]: column

print(f"Select col 0 of B: B[ : , 0 ] = {B[:, 0]}")
print(f"Select row 1 of B: B[ 1 , : ] = {B[1, :]}")
print(f"Select element in row = 1 , col = 1 , B[row, col] or B[row][col] = {B[1, 1]}")
print(f"The size of B = (B.shape[0], B.shape[1]) = {B.shape[0], B.shape[1]}")
print(f"The size of B = B.shape = {B.shape}")

Select col 0 of A: A[ : , 0 ] = [2 4 1]
Select row 2 of A: A[ 2 , : ] = [1 1]
Select element in row = 0 , col = 1 , A[row, col] or A[row][col] = 3
The size of A = (A.shape[0], A.shape[1]) = (3, 2)
Select col 0 of B: B[ : , 0 ] = [5 7]
Select row 1 of B: B[ 1 , : ] = [7 8]
Select element in row = 1 , col = 1 , B[row, col] or B[row][col] = 8
The size of B = (B.shape[0], B.shape[1]) = (2, 2)
The size of B = B.shape = (2, 2)


### **Apply algorithm: loop 1 is ith row of A, loop 2 is jth colum n of B, and loop three is kth column of A (kth row of B)**

In [34]:
# intialize the final matrix

AB = np.empty((3, 2))

for i in range(n_row_A):
    for j in range(B.shape[1]):
        elem = 0
        for k in range(n_col_A):
            elem += A[i][k] * B[k][j]
        AB[i, j] = elem

print(f"AB with loops = \n{AB}")
print(f"AB with python library = \n{A @ B}")
print(f"The difference = \n{AB - A @ B}")

AB with loops = 
[[31. 36.]
 [55. 64.]
 [12. 14.]]
AB with python library = 
[[31 36]
 [55 64]
 [12 14]]
The difference = 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


---
### **$\color{brown}{\textbf{TODO 3: }}$** Follow the same as **TODO 2** to implement the **"layer perspective"** matrix multiplication of matrices $\mathbf{A}$ and $\mathbf{B}$ with integer elements matrices of small sizes.

---
### **$\color{brown}{\textbf{TODO 4: }}$** Follow the same as **TODO 2** to implement the **"column" perspective** matrix multiplication of matrices $\mathbf{A}$ and $\mathbf{B}$ with integer elements matrices of small sizes.



---
### **$\color{brown}{\textbf{TODO 5: }}$** Follow the same as **TODO 2** to implement the **"row" perspective** matrix multiplication of matrices $\mathbf{A}$ and $\mathbf{B}$ with integer elements matrices of small sizes.

---
### **$\color{brown}{\textbf{TODO 6: }}$ Create an App of matrix multiplication of four perspectives** 



* User input of sizes of a matrix. You can use any of the input formats available in google colab form
* Use random numbers for the matrices $\mathbf{A}$ and $\mathbf{B}$
* print out the name of the perspective chosen
* print out the matrix AB with 1 decimal places.

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# **$$ ⛳ \textbf{ Build Matrix Multiplication Layer-Wise with Outer Product }⛳ $$**

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## **Objective:**
####  Explore the layer perspective of matrix in a little bit more detail. In particular, what you are going to implement matrix multiplication via layering with four loops and the outer product

---
### **$\color{brown}{\textbf{TODO 7: }}$** Follow the suggested steps to implement the **"Layper" perspective** matrix multiplication using outer products for experimentation.



#### 🎨 $\color{darkorange}{\text{ TIP: Test your for-loop with a small sized matices with integer elements.}}$ 


#### **1.** Define two variables as row and column numbers.
#### **2.** Generate **two random number matrices** of dimentions specified by the variable in **1.**
#### **3.** Build the product of the two matrices layer-wise:
<details>
  <summary><b>Show Diagrams Algorithm of Layer-Wise Multiplication with For-Loop</b></summary>

  
<p style="text-align:center;"><img src = "https://drive.google.com/uc?id=1lkJLmCEPX2hrUeV4gOB7FdiQtHdkd84F" width = "2000px" height = "480px" />
</details>
*  Write a for-loop (layers) that goes over all of the columns of the left matrix and all the rows of the right matrix.
*  Compute the outer product between each corresponding column of the left matrix and row of the right matrix and then add all of those layers up to give you the the final product of the two matrices.

#### **4.** Compute the product directly using Python library
#### **5.** Print the different of the matrix multiplciation from 3 and 4.  


---
### **$\color{brown}{\textbf{TODO 8: }}$ Running experiments using your code**

#### **1.** Run your experiments many times with different dimentions

#### **2.** Document the data and results in a markdown cells

#### **3.** Why are the different of the matrix products from the layer and direct methods not all zero? 

##### ✅ **$\color{darkorange}{\textbf{There are many different versions of solutions}}$**

---
### **$\color{brown}{\textbf{TODO 9: }}$ Make your conclusion based on your experiment** 



The matrix products using Layer-wise and direct computation is the same with precision up to $10^{-15}$ decimal places.