![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)
# **$$ ⛳ \textbf{ Demo for HW with Code: }⛳ $$**
## **$$\color{purple}{\textbf{ Is Dot Product Associative?}}$$**


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## **Objectives** 

To prove that dot product is not associative.
To find out special cases when the dot product is associative.


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## **TODOs** 

---
### **$\color{brown}{\textbf{TODO 1: }}$ State your hypothesis**

####Given three column vectors $\mathbf{a}$, $\mathbf{b}$ and $\mathbf{c}$ with the same dimentionality $n$, then
#### $$\LARGE \mathbf{a}^\text{T}\underbrace{\mathbf{(b}^\text{T}\mathbf{c)} }_{\color{green}{\textbf{Scalar}}}\, \color{red}{\ne} \,  \underbrace{(\mathbf{a}^{\text{T}}\mathbf{b}}_{\color{green}{\textbf{Scalar}}} )^\text{T}\mathbf{c}$$

---
### **$\color{brown}{\textbf{TODO 2: }}$  Writing code for experiments**
* Define three dimension veriables (soft code)
* Create one radom vector with each of the three dimension you defined in the previous step using [`numpy.random.randn(size)`](https://numpy.org/doc/1.16/reference/routines.random.html)
* Compute the left $ \mathbf{a}^\text{T}\mathbf{(b}^\text{T}\mathbf{c)}$ and right side $(\mathbf{a}^{\text{T}}\mathbf{b} )^\text{T}\mathbf{c}$ of the definition of associative property of dot productive

* Compare the results of left and right side
* Print out the vectors, the left and right side of the associative property formula and their difference

In [ ]:
import numpy as np
# 1. define 3 dimensional variables
n = 5
m = 5
k = 5

# create 3 random vectors corresponding to the 3 dimensions
a = np.random.randn(n)
b = np.random.randn(m)
c = np.random.randn(k)

# calculate the left and right side of the associative property
left = np.dot(a, np.dot(b, c))
right = np.dot(np.dot(a, b), c)

# compare the answers
print(f"vector a = {a}")
print(f"vector b = {b}")
print(f"vector c = {c}")
print(f"\n left and right sides of the associative property formula")
print(f" left = {left}")
print(f"right = {right}")
print(f"\n difference between the left and the right side of the associative property\n{left - right}")

vector a = [ 1.27036418 -0.90749466 -0.97790125  1.00796561 -1.4743316 ]
vector b = [ 0.51247752  0.54399831  1.52171174 -0.85146459 -1.78436478]
vector c = [-0.27199246 -1.02838856  0.57310423 -0.94975096 -0.94876437]

 left and right sides of the associative property formula
 left = [ 3.39808295 -2.42744732 -2.61577713  2.69619595 -3.94367312]
right = [-0.12015867 -0.45431333  0.25318144 -0.41957344 -0.41913759]

 difference between the left and the right side of the associative property
[ 3.51824162 -1.97313398 -2.86895856  3.11576939 -3.52453553]


---
### **$\color{brown}{\textbf{TODO 3: }}$ Experiment with your code**
* Write a title in mardown cell to describe your experiment
* copy the code above and modify if necessary
* add soft code 
  initialize a counter
  run your experiment for over 10000 times and count   
  modify your print out for your code.
* Run your experiment once and print out the details and record results.
* Run your experiment over 1000 times (soft code) and only print out the counter values

#### **1. All vectors with the same dimentions**

In [ ]:
#@title All vectors same dimension test
import numpy as np
# 1. define 3 dimensional variables
n = 5
m = 5
k = 5

count_false = 0

for i in range(10000):
    # create 3 random vectors corresponding to the 3 dimensions
    a = np.random.randn(n)
    b = np.random.randn(m)
    c = np.random.randn(k)

    # calculate the left and right side of the associative property
    left = np.dot(a, np.dot(b, c))
    right = np.dot(np.dot(a, b), c)
    if np.array_equal(left, right):
        count_false += 1

# compare the answers
# print(f"vector a = {a}")
# print(f"vector b = {b}")
# print(f"vector c = {c}")
# print(f"\n left and right sides of the associative property formula")
# print(f" left = {left}")
# print(f"right = {right}")
# print(f"\n difference between the left and the right side of the associative property\n{left - right}")

print(f"The number of left and right side are equal in the associative property is {count_false}")

The number of left and right side are equal in the associative property is 0


#### **2. The left vector has different dimentions from the two right vectors**

In [ ]:
#@title NOT VALID
import numpy as np
# 1. define 3 dimensional variables
n = 5
m = 3
k = 3

count_false = 0

for i in range(10000):
    # create 3 random vectors corresponding to the 3 dimensions
    a = np.random.randn(n)
    b = np.random.randn(m)
    c = np.random.randn(k)

    # calculate the left and right side of the associative property
    left = np.dot(a, np.dot(b, c))
    right = np.dot(np.dot(a, b), c)
    if np.array_equal(left, right):
        count_false += 1

# compare the answers
# print(f"vector a = {a}")
# print(f"vector b = {b}")
# print(f"vector c = {c}")
# print(f"\n left and right sides of the associative property formula")
# print(f" left = {left}")
# print(f"right = {right}")
# print(f"\n difference between the left and the right side of the associative property\n{left - right}")

print(f"The number of left and right side are equal in the associative property is {count_false}")

ValueError: ignored

#### **3: Special Case** All vectors with the same dimention and one of the vector is zero.:

In [ ]:
#@title All same dimension, one vector is 0
import numpy as np
# 1. define 3 dimensional variables
n = 5
m = 5
k = 5

count_false = 0

for i in range(10000):
    # create 3 random vectors corresponding to the 3 dimensions
    a = np.zeros(n)         # a = [0] * n
    b = np.random.randn(m)
    c = np.random.randn(k)

    # calculate the left and right side of the associative property
    left = np.dot(a, np.dot(b, c))
    right = np.dot(np.dot(a, b), c)
    if np.array_equal(left, right):
        count_false += 1

# compare the answers
print(f"vector a = {a}")
print(f"vector b = {b}")
print(f"vector c = {c}")
print(f"\n left and right sides of the associative property formula")
print(f" left = {left}")
print(f"right = {right}")
print(f"\n difference between the left and the right side of the associative property\n{left - right}")

print(f"The number of left and right side are equal in the associative property is {count_false}")

vector a = [0. 0. 0. 0. 0.]
vector b = [-1.07629862 -0.5518099   1.7760588  -0.83758802  1.53198085]
vector c = [-1.3569327  -1.88779482  0.11932876  1.35878669  0.18271318]

 left and right sides of the associative property formula
 left = [0. 0. 0. 0. 0.]
right = [0. 0. 0. 0. 0.]

 difference between the left and the right side of the associative property
[0. 0. 0. 0. 0.]
The number of left and right side are equal in the associative property is 10000


#### **In this special case, the dot product is associative**

##### **4: Scecial Case** all vectors are equal

In [ ]:
#@title All vectors are equal
import numpy as np
# 1. define 3 dimensional variables
n = 5
m = 5
k = 5

count_false = 0

for i in range(10000):
    # create 3 random vectors corresponding to the 3 dimensions
    b = np.random.randn(m)
    a = c = b

    # calculate the left and right side of the associative property
    left = np.dot(a, np.dot(b, c))
    right = np.dot(np.dot(a, b), c)
    if np.array_equal(left, right):
        count_false += 1

# compare the answers
print(f"vector a = {a}")
print(f"vector b = {b}")
print(f"vector c = {c}")
print(f"\n left and right sides of the associative property formula")
print(f" left = {left}")
print(f"right = {right}")
print(f"\n difference between the left and the right side of the associative property\n{left - right}")

print(f"The number of left and right side are equal in the associative property is {count_false}")

vector a = [-0.90059681 -0.60834852 -0.4918409  -0.08474153  1.40889159]
vector b = [-0.90059681 -0.60834852 -0.4918409  -0.08474153  1.40889159]
vector c = [-0.90059681 -0.60834852 -0.4918409  -0.08474153  1.40889159]

 left and right sides of the associative property formula
 left = [-3.07574223 -2.07764806 -1.67974816 -0.28941152  4.81168409]
right = [-3.07574223 -2.07764806 -1.67974816 -0.28941152  4.81168409]

 difference between the left and the right side of the associative property
[0. 0. 0. 0. 0.]
The number of left and right side are equal in the associative property is 10000


---
### **$\color{brown}{\textbf{TODO 4: }}$ Discussion and Conclusion**

**Conclusion** vector **a**, **b**, and **c** are equal. The associative property of dot product works. 10000 out of 10000 runs return successful.

#### Given three column vectors $\mathbf{a}$, $\mathbf{b}$ and $\mathbf{c}$ with the same dimentionality $n$, then
#### $$
\LARGE \mathbf{a}^\text{T}\underbrace{\mathbf{(b}^\text{T}\mathbf{c)} }_{\color{green}{\textbf{Scalar}}}\, \color{red}{\ne} \,  \underbrace{(\mathbf{a}^{\text{T}}\mathbf{b}}_{\color{green}{\textbf{Scalar}}} )^\text{T}\mathbf{c}
$$

**Proof**

$$
\LARGE 
\,
\substack{
    \mathbf{a} \text{ ∈ } \mathbb{R}^{3} \\
    \mathbf{b, \text{ } c} \text{ ∈ } \mathbb{R}^{3}
}
\,
\implies
\overbrace{
\mathbf{a}^\text{T}\underbrace{\mathbf{(b}^\text{T}\mathbf{c)} }_{\color{green}{\textbf{Scalar}}}
}^{\color{orange}{\text{left side}}}
\, \color{red}{\ne} \,  
\overbrace{
\underbrace{(\mathbf{a}^{\text{T}}\mathbf{b}}_{\color{green}{\mathbb{R}^{5} \times \mathbb{R}^{3}}} )^\text{T}\mathbf{c}
}^{\color{orange}{\text{right side}}}
$$