![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)
# **$$ ⛳ \textbf{  The Outer Product }⛳ $$**




![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## **Objectives** 

By the end of this lesson, you will:

#### - Know what outer product is and its difference from dot product

#### - Learn two ways to conceptualize the outer product
#### - Identify subtle Python code difference between outer- and dot- product 

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## **Outer Product Notation** 


$$\LARGE \text{Dot product: }\hspace{15mm}\color{blue}{\underset{\text{N}\color{black}{\times} 1}{\mathbf{v}^{\text{T}}}}\color{magenta}{\underset{\text{N}\color{black}{\times} 1}{\mathbf{w}}} = \color{blue}{1}\times \color{magenta}{1} \quad\quad= \quad\text{A Number}$$
\\
$$\LARGE\text{Outer product: }\hspace{10mm}\color{blue}{\underset{\text{N}\color{black}{\times} 1}{\mathbf{v}}}\color{orange}{\underset{\text{M}\color{black}{\times} 1}{\mathbf{w}^{\text{T}}}} = \color{blue}{N}\times \color{orange}{M} \quad= \quad\text{A Matrix}$$

* The result of the DOT product is a **single number, a scalar,** regardless of the dimentionality of these two vectors as long as the two vectors have the same number of elements
* The outer product, in contrast, is not a single number, but instead it's a **matrix** and the outer product is notated by transposing the second vector and not the first vector.

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## **Outer as scaling of the column elements of the first vector by the row elements of the transpose of the second,or vice versa** 

###$$\LARGE
  \begin{align}
   \color{blue}{\textbf{v}} \color{magenta}{\textbf{w}}^{\text{T}} \, 
   =& \,\,\
    \color{blue}{\begin{bmatrix}
    0 \\
    1 \\
    2 \\
    3
    \end{bmatrix}
  }\, 
  \color{magenta}{\begin{bmatrix}
    a & b & c & d & e\\
    \end{bmatrix} \\
  }\\
   = & \quad
\begin{bmatrix}
\color{blue}{0} \cdot \color{magenta}{a} \,&\, \color{blue}{0} \cdot \color{magenta}{b}\,&\, \color{blue}{0} \cdot \color{magenta}{c}\,&\, \color{blue}{0} \cdot \color{magenta}{d}\,&\, \color{blue}{0} \cdot \color{magenta}{e}\\
\color{blue}{1}  \cdot \color{magenta}{a} \,&\, \color{blue}{1} \cdot \color{magenta}{b}\,&\, \color{blue}{1} \cdot \color{magenta}{c}\,&\, \color{blue}{1} \cdot \color{magenta}{d}\,&\, \color{blue}{1} \cdot \color{magenta}{e}\\
\color{blue}{2} \cdot \color{magenta}{a}\, &\, \color{blue}{2} \cdot \color{magenta}{b}\,&\, \color{blue}{2} \cdot \color{magenta}{c}\,&\, \color{blue}{2} \cdot \color{magenta}{d}\, &\, \color{blue}{2} \cdot \color{magenta}{e}\\
\color{blue}{3} \cdot \color{magenta}{a}\, &\, \color{blue}{3} \cdot \color{magenta}{b}\,&\, \color{blue}{3} \cdot \color{magenta}{c}\,&\, \color{blue}{3} \cdot \color{magenta}{d}\, &\, \color{blue}{3} \cdot \color{magenta}{e}\\
\end{bmatrix}
\end{align}
  $$

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
## **🔖 $\color{blue}{\textbf{ Practice: }}$ Python for Computing Outer Product**

### **Method 1: Use native Python for-loop with definition of outer producrt**
* How to initialize a [zero matrix](https://www.geeksforgeeks.org/numpy-zeros-python/) of dimention $m\times n$



In [5]:
import numpy as np

# Create two vectors as numpy array and not list so that you can perform arithmetic operations with them
v = np.array([  1, 2, 3 ])
w = np.array([ -1, 0, 1, -1 ])

# initialize a zero matrix with row and column numbers = dimentions of vectors v and w
op_vw = np.zeros((len(v),len(w))) # zeros((row, col)) the inside parenthesis is or setting dimensions

# Loop through each element of the first vector v
for i in range(0, len(v)): # default range(len(v)) the inside parenthesis is for default dimensions
    # Loop through each element of the second vector w
    for j in range(0, len(w)):
        op_vw[i,j] = v[i] * w[j]

print(f"Vector v = {v} \nVector w = {w}\n")
print(f"Using definition, the outer product of v and w: \n vw^T = \n{op_vw}")

Vector v = [1 2 3] 
Vector w = [-1  0  1 -1]

Using definition, the outer product of v and w: 
 vw^T = 
[[-1.  0.  1. -1.]
 [-2.  0.  2. -2.]
 [-3.  0.  3. -3.]]


### **Method 2: Use Python numpy library [`numpy.outer()`](https://www.pythonpool.com/numpy-outer/)**

In [6]:
# two vectors
v1 = np.array([  1, 2, 3 ])
v2 = np.array([ -1, 0, 1 ])

# outer product
op_vw = np.outer(v,w)

print(f"Vector v = {v} \nVector w = {w}\n")
print(f"Using np.outer(), the outer product of v and w: \nvw^T = \n{op_vw}")

Vector v = [1 2 3] 
Vector w = [-1  0  1 -1]

Using np.outer(), the outer product of v and w: 
vw^T = 
[[-1  0  1 -1]
 [-2  0  2 -2]
 [-3  0  3 -3]]
